### ISSUE TITLE
SIARDDK: update standard schemas

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#223]
Due to an upgrade for the SIARDDK validator "ADA", the DNA will make changes in some of the mandatory standard schemas.

Here is the revised `Schemas\standard` subfolder with all necessary schemas:
Edit 19/9 
[standard.zip](https://github.com/keeps/db-preservation-toolkit/files/479428/standard.zip)

DBPTK for SIARDDK export module should create this revised folder instead of the current.

Best regards
-Phillip

**Comment by PhillipTommerholt** [comment]
Info: there are only minor revisions in two of the schemas:
-fileIndex.xsd: revisions due to IPs with GML, not relevant for DBPTK other than that the revised fileIndex.xsd has to be in the standard folder..
tableIndex.xsd, the datatype INTERVAL is now allowed to appear only as INTERVAL in tableIndex.xml.

**Comment by PhillipTommerholt** [comment]
New updated schemas folder.
Schemas also allow wav-files in document folders.
[standard.zip](https://github.com/keeps/db-preservation-toolkit/files/466986/standard.zip)

**Comment by andreaskring** [comment]
@PhillipTommerholt Fixed in #261 . Could you please check, if it is working ok in your end?

**Comment by PhillipTommerholt** [comment]
This is not fixed.
The schemas has been altered to include .bin files in document folders.
These are not allowed in SIARDDK and it is not allowed to alter the standard schemas, see 4.F.2 in bek. 1007 and appendix 8.
We should talk about this on Skype before fixing this :-)

**Comment by PhillipTommerholt** [comment]
It is a small detail, not an urgent issue.

**Comment by chalkos** [comment]
@andreaskring tell me if you need me to upload a new bindings-siarddk to artifactory, so travis can use it. I can fetch your branch and deploy your new version (just make sure to bump version numbers every time you make changes to the bindings-siarddk, otherwise strange problems may appear).

**Comment by andreaskring** [comment]
@PhillipTommerholt About the .bin files - we have a small problem with these... I had to change the XML schemas a bit in order for allowing the .bin files during export - otherwise the JAXB lib will fail when marshalling. I agree that we should have a talk about this problem on Skype. @chalkos Ok thanks. I will notify you when I have to make changes to bindings-siarddk.

**Comment by PhillipTommerholt** [comment]
[standard.zip](https://github.com/keeps/db-preservation-toolkit/files/479426/standard.zip)
Final schema folder.

**Comment by andreaskring** [comment]
The necessary changes have been made - @PhillipTommerholt is currently testing these
